### ISSUE TITLE
E-mail report could be more detailed and understandable

### ISSUE THREAD

**Issue by surphil** [nitsan-technologies/ns_ext_compatibility#13]
We want to use the great email report to send automatic notifications to customers. I think some points could be optimized:

- Show installed TYPO3 Version and latest TYPO3 Version (sth. like "Installed Version 8.7.22 / Latest Version 8.7.26 / no-security updates")
- Show on updates for extensions, if these are security relevant

**Comment by nitsan-technologies** [comment]
Hey @surphil 

Thank you for your suggestion.
We have adapted your changes and uploaded at GIT repository.
You can download it from here (https://github.com/nitsan-technologies/ns_ext_compatibility/)
Soon we will upload at TER too.

You can suggest more features too. So that we can improve it. 

Cheers!
Team NITSAN
